host_name: vsrx01
host:
    loopback:
        ip: 10.20.1.1
underlay:
    local:
        asn: 104
    neighbors:
      - interface: ge-0/0/1
        name: to vsrx02
        asn: 109
        peer_ip: 192.168.0.1
        local_ip: 192.168.0.0
      - interface: ge-0/0/2
        name: to vsrx03
        asn: 110
        peer_ip: 192.168.0.3
        local_ip: 192.168.0.2
